from bot_app.commands.start import *
from bot_app.commands.set_city import *
from bot_app.commands.help import *
from bot_app.commands.change_sity import *
from bot_app.commands.get_location import *
from bot_app.commands.get_contacts import *
from bot_app.commands.get_menu import *
from bot_app.commands.reverve_table import *
from bot_app.commands.my_bookings import *