# Generated by Django 4.0.3 on 2022-03-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'Cities',
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_id', models.PositiveSmallIntegerField(choices=[(1, 'Kyiv'), (2, 'Dnipro'), (3, 'Lviv'), (4, 'Kharkiv'), (5, 'Odessa')], default=2)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('open_at', models.CharField(max_length=20)),
                ('close_at', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='photos')),
                ('rating', models.CharField(max_length=30)),
                ('is_delivery', models.BooleanField()),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'Restaurants',
            },
        ),
    ]
