# Generated by Django 4.0.3 on 2022-03-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='city_id',
        ),
    ]
