# Generated by Django 4.0.3 on 2022-03-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_remove_restaurants_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='city_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kyiv'), (2, 'Dnipro'), (3, 'Lviv'), (4, 'Kharkiv'), (5, 'Odessa')], default=2),
        ),
    ]
