# Generated by Django 4.0.3 on 2022-03-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_alter_restaurants_city_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='name',
            new_name='city',
        ),
    ]
