# Generated by Django 4.0.3 on 2022-03-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_alter_restaurants_city_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='city',
            new_name='name',
        ),
    ]
