# Generated by Django 4.0.3 on 2022-03-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_rename_city_cities_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cities',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='restaurants',
            table='restaurants',
        ),
    ]
