# Generated by Django 4.0.3 on 2022-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_alter_cities_table_alter_restaurants_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.FloatField(),
        ),
    ]
