# Generated by Django 4.0.3 on 2022-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0015_alter_users_country_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='country',
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
