# Generated by Django 4.0.3 on 2022-03-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0017_alter_users_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
    ]
