# Generated by Django 4.0.3 on 2022-03-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0018_remove_users_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_app.cities', verbose_name='city'),
        ),
    ]
