# Generated by Django 4.0.3 on 2022-03-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0019_users_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='city',
            new_name='city_id',
        ),
    ]
