# Generated by Django 4.0.3 on 2022-03-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0020_rename_city_users_city_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='city_id',
            new_name='city',
        ),
    ]
