# Generated by Django 4.0.3 on 2022-03-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0021_rename_city_id_restaurants_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
