# Generated by Django 4.0.3 on 2022-03-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0022_restaurants_lat_restaurants_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantsMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='photos')),
                ('type', models.CharField(choices=[(1, 'MENU'), (2, 'BAR')], max_length=10)),
                ('restaurant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_app.restaurants', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'restaurant_menu',
                'verbose_name_plural': 'Restaurants Menu',
                'db_table': 'restaurants_menu',
            },
        ),
    ]
