# Generated by Django 4.0.3 on 2022-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0025_alter_restaurantsmenu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsmenu',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MENU'), (1, 'BAR')], default=0),
        ),
    ]
