# Generated by Django 4.0.3 on 2022-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0028_alter_restaurantsmenu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsmenu',
            name='type',
            field=models.CharField(choices=[('MENU', 'MENU'), ('BAR', 'BAR')], default='MENU', max_length=10),
        ),
    ]
