# Generated by Django 4.0.3 on 2022-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0031_alter_reservations_options_alter_reservations_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='comment_by_restaurant',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('ON_REVIEW', 'ON_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='MENU', max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurantsmenu',
            name='type',
            field=models.CharField(choices=[('MENU', 'MENU'), ('BAR', 'BAR')], default='DRAFT', max_length=10),
        ),
    ]
