# Generated by Django 4.0.3 on 2022-03-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0032_reservations_comment_by_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='contact_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='contact_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='number_of_people',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_app.restaurants', verbose_name='restaurant'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
