# Generated by Django 4.0.3 on 2022-03-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0033_alter_reservations_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='contact_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='number_of_people',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
