# Generated by Django 4.0.3 on 2022-03-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0034_alter_reservations_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='place',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
