# Generated by Django 4.0.3 on 2022-03-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0035_restaurants_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='place',
            new_name='places',
        ),
    ]
